### ISSUE TITLE
建议把取消图片的代理给开放出来

### ISSUE THREAD

**Issue by nemofun** [iphone5solo/PYPhotoBrowser#10]
建议把取消图片的代理给开放出来

**Comment by iphone5solo** [comment]
取消图片？ 指的是哪个？

**Comment by nemofun** [comment]
就是发布图片的时候选择了图片出来，不是可以点击右上角的x号取消么，这里能加一个代理出来会比较方便做一些自适应的布局

**Comment by iphone5solo** [comment]
好的 谢谢您的反馈、 我最近回家休息。没带电脑。 过几天就开放这个代理

**Comment by iphone5solo** [comment]
现在已经开放发布前图片预览的预览控制器。 可以通过photosView:didPreviewImagesWithPreviewControlelr: 代理方法获取预览控制器。实现自定义预览时的状态栏。欢迎下载最新版测试使用
