### ISSUE TITLE
初始化设置图片高度的时候不管用

### ISSUE THREAD

**Issue by yunlgtao** [iphone5solo/PYPhotoBrowser#11]
开始时的设置了宽高，发现宽正常，高没有执行。当点击了一下图片，查看了一次大图后，返回时高变正常。还有就是，如果不设置缩略图数，我发现会自动加载大图，这样不是很好吧？

**Comment by iphone5solo** [comment]
谢谢您的反馈，BUG 会尽快修复。 关于没有设置缩略图会自动加载大图。 这是为了可以显示图片。 个人觉得比较的处理。如果您在使用的过程中觉得不合理。可以自己稍微修改代码。
