### ISSUE TITLE
cell复用时，图片个数会出问题

### ISSUE THREAD

**Issue by ygmtx** [iphone5solo/PYPhotoBrowser#12]
是否方便弄个动态图，这样更能显示出问题的所在。

**Comment by iphone5solo** [comment]
此BUG已经修复，请下载最新版测试！ 谢谢反馈 @ygmtx

**Comment by xiangyu-czc** [comment]
你是怎么在cell上显示的，能给个demo吗，我在cell上显示非常卡顿，我QQ525713029

**Comment by iphone5solo** [comment]
@xiangyu-czc  加你QQ了给你写了个Demo
