### ISSUE TITLE
如何在点击我自己的UIImageView后，直接使用PYPhotoBrowseView

### ISSUE THREAD

**Issue by syxiaqj** [iphone5solo/PYPhotoBrowser#16]
点击UIImageView而不是PYPhotoView，如何只调用PYPhotoBrowseView，并加载大图

**Comment by iphone5solo** [comment]
@syxiaqj 在点击UIImageView后
    // 1. 创建photoBroseView对象
    PYPhotoBrowseView *photoBroseView = [[PYPhotoBrowseView alloc] init];

    // 2.1 设置图片源(UIImageView)数组
    photoBroseView.sourceImgageViews = imageViews;
    // 2.2 设置初始化图片下标（即当前点击第几张图片）
    photoBroseView.currentIndex = 2;

    // 3.显示(浏览)
    [photoBroseView show];

**Comment by syxiaqj** [comment]
在不使用PYPhoto的情况下，如何从缩略图加载到大图？

**Comment by iphone5solo** [comment]
设置photoBrowseView的imageUrls属性把原图链接传进去，详情见PYPhotoBrowseView.h
