### ISSUE TITLE
PYPhotoBrowseView类里面为什么取消了网路图片url数组元素？

### ISSUE THREAD

**Issue by louyaowen** [iphone5solo/PYPhotoBrowser#19]
PYPhotoBrowseView类里面为什么取消了网路图片url数组元素？现在直接浏览图片需要传递UIImage数组，而且还崩溃~

**Comment by iphone5solo** [comment]
因为PYPhotoBrowseView 是用于单纯的图片浏览。 即用户已经下载好图片，所以传的是图片UIImageView数组 至于你传入数组为何会崩溃，还望详细描述一下！ @louyaowen

**Comment by louyaowen** [comment]
这样是有一点不方便，我需要在一个循环里面异步下载每一张图片,放在数组里，然后[PYPhotoBrowser show]，可以考虑一下增加接口，直接传入URL数组就可实现~之前的崩溃好像是因为图片还没有下载好久直接调用[PYPhotoBrowser show]导致的~

**Comment by iphone5solo** [comment]
懂了，谢谢你的反馈，给我一点时间！ @louyaowen

**Comment by iphone5solo** [comment]
@louyaowen 麻烦加一下我QQ 我了解一下bug的详情！

**Comment by louyaowen** [comment]
嗯好的~
