### ISSUE TITLE
预览大图的时候支持图片删除功能吗？怎么删除按钮显示不出来呢？大神，求解！！

### ISSUE THREAD

**Issue by ETmanwenhan** [iphone5solo/PYPhotoBrowser#20]
预览大图的时候支持图片删除功能吗？怎么删除按钮显示不出来呢？大神，求解！！

**Comment by iphone5solo** [comment]
请详细描述一下您的问题，你在要发布图片状态么？ @ETmanwenhan

**Comment by ETmanwenhan** [comment]
PYPhotosPreviewController 类 

readerVc.navigationItem.rightBarButtonItem = [[UIBarButtonItem alloc] initWithBarButtonSystemItem:UIBarButtonSystemItemTrash target:readerVc action:@selector(trashDidClicked)];

这里的rightBarButtonItem  删除按钮怎么不显示呢？纳闷中...

**Comment by iphone5solo** [comment]
@ETmanwenhan  加我QQ 499491531 备注：GitHub

**Comment by ETmanwenhan** [comment]
加了
