### ISSUE TITLE
一个小建议

### ISSUE THREAD

**Issue by SimpleWQ** [iphone5solo/PYPhotoBrowser#21]
今天看你的源码的时候发现if语句后没有跟上{}，虽然没有问题，但是个人觉得这不是一个好习惯。一个小建议而已。

**Comment by iphone5solo** [comment]
@SimpleWQ 谢谢你的建议！ 因为只是一行，所以故意不加上{ }，(PS：个人感觉比较美观)，如果工作有要求，肯定是按照要求来的。其他都是按照规范来的。
