### ISSUE TITLE
 希望能提供对本地图片缩放交互  另感谢大神提供这么好用的photoBrowser

### ISSUE THREAD

**Issue by wufer** [iphone5solo/PYPhotoBrowser#23]
ps：py......

**Comment by iphone5solo** [comment]
@wufer  你好，谢谢您的反馈。 最近事情比较多。 所以github主要是修复bug. 拓展模块还是等时间多了再弄， 您也可以自己先尝试着弄一下。
ps：py只是名字首拼，所以.......
