### ISSUE TITLE
不支持 Swift?

### ISSUE THREAD

**Issue by chuyik** [iphone5solo/PYPhotoBrowser#24]
我的 Swift 编译提示 Could not build Objective-C module 'PYPhotoBrowser'：
![image](https://cloud.githubusercontent.com/assets/6262943/20244073/71a7d626-a9ad-11e6-9c53-f4ed1e51d882.png)

Podfile 如下：
```ruby
platform :ios, '9.0'
use_frameworks!

target 'MyNewDemo' do
  pod 'PYPhotoBrowser'
end
```

**Comment by iphone5solo** [comment]
@chuyik  是的 因为我Swift接触得比较少，所以暂时不支持Swift!
