### ISSUE TITLE
删除图片出现问题

### ISSUE THREAD

**Issue by Kyoooooo** [iphone5solo/PYPhotoBrowser#25]
点击最后一张图片预览，点击删除，屏幕变黑，要滑动才能恢复

**Comment by iphone5solo** [comment]
@Kyoooooo  谢谢您的反馈，晚上回去我看看，尽快修复！

**Comment by iphone5solo** [comment]
@Kyoooooo  你好，可否详细描述一下操作和环境，我这边这次没有发现您所说的bug

**Comment by Kyoooooo** [comment]
我是用5s，ios8的系统，操作步骤就是运行，点击右上角发布，然后点击加号添加几张图片，然后点左后一张图片进入预览，然后点右上角的删除图标，点删除，然后就黑屏了

**Comment by iphone5solo** [comment]
@Kyoooooo   加我QQ499491531 备注：github#25
