### ISSUE TITLE
图片浏览时，点击图片应该缩小然后移除，但是你这个会先放大然后消失

### ISSUE THREAD

**Issue by xiongoahc** [iphone5solo/PYPhotoBrowser#27]

**Comment by iphone5solo** [comment]
@xiongoahc 
很可能你没有设置这两个个参数 
/** 默认显示图片相对于主窗口的位置(即从窗口的哪个位置显示)，
 * 注意：设置此属性时，showFromView属性失效
 */
@property (nonatomic, assign) CGRect frameFormWindow;

/** 消失回到相对于住窗口的指定位置(即消失在窗口的哪个位置)
 * 注意：设置此属性时，hiddenToView属性失效
 */
@property (nonatomic, assign) CGRect frameToWindow;
