### ISSUE TITLE
PYPhotoBrowseView 浏览图片切换横屏时bug

### ISSUE THREAD

**Issue by dzqing1943** [iphone5solo/PYPhotoBrowser#31]
PYPhotoBrowseView 传入了uiimgeview 数组后· 竖屏显示正常，也可翻页查看其他图片，但是如果初始化后第一时间由竖着显示切换成横屏后，再翻页查看其他图就闪退。

**Comment by iphone5solo** [comment]
现在已经修复，欢迎下载最新版测试！ @dzqing1943
