### ISSUE TITLE
出现和消失  动画

### ISSUE THREAD

**Issue by bidm** [iphone5solo/PYPhotoBrowser#35]
出现和消失的动画时间太久了   怎么改

**Comment by iphone5solo** [comment]
@bidm  您好！ 根据您的需求 以提供相应属性来设：
/** 显示动画时长：（默认0.5s） */
@property (nonatomic, assign) CGFloat showDuration;
/** 隐藏动画时长：（默认0.5s） */
@property (nonatomic, assign) CGFloat hiddenDuration;
