### ISSUE TITLE
UINavigationBar appearance 会影响preview的导航样式

### ISSUE THREAD

**Issue by duwenqi** [iphone5solo/PYPhotoBrowser#37]
如果我在app当中设置了NavigationBar 的appearance， 会影响preview VC 的样式，应该怎么解决。

**Comment by iphone5solo** [comment]
@duwenqi   建议您看一下这篇文章：iOS UIAppearance使用详解http://blog.sina.com.cn/s/blog_9693f61a0101f1rs.html

**Comment by duwenqi** [comment]
Hi @iphone5solo 我的意思是我觉得一个比较优秀的开源库，是应该能有效的避免使用者在使用时对上下文环境的污染所造成的影响，包括你使用一些比较知名的SDK 他们都会针对这方面做处理，用来防止一些情况下导致SDK内部的一些逻辑、样式等发生一些不可预知的改变。

**Comment by iphone5solo** [comment]
@duwenqi 谢谢您的建议，我尽量找到解决方案，如果您有比较好的解决方案，欢迎 pull request!

**Comment by iphone5solo** [comment]
@duwenqi  我今天测试了下，NavigationBar 的appearance，没有影响到preview VC 的样式

**Comment by duwenqi** [comment]
[[UINavigationBar appearance] setBackgroundImage:[UIImage imageNamed@"xxx"]]
                                      forBarPosition:UIBarPositionAny
                                          barMetrics:UIBarMetricsDefault];

**Comment by iphone5solo** [comment]
@duwenqi 谢谢您的反馈，确实存在问题，现在已经修复，欢迎下载最新/pod update 测试！
