### ISSUE TITLE
滑动最后一张时，会崩溃

### ISSUE THREAD

**Issue by JsonFu** [iphone5solo/PYPhotoBrowser#39]
在page崩溃的地方加上判断 ：
self.pageControl.currentPage = page;
    // 取出photosView
    PYPhotosView *photosView = self.selectedPhotoView.photosView;
    if (page >photosView.subviews.count) {
        page = page-1;
         self.selectedPhotoView = photosView.subviews[page];
    }

**Comment by iphone5solo** [comment]
@JsonFu  麻烦报错的时候截一下图或者弄个Gif 这样错误更明显！
