### ISSUE TITLE
模拟器运行有点小问题

### ISSUE THREAD

**Issue by NateLam** [iphone5solo/PYPhotoBrowser#40]
我使用您的三方进行全屏大图展示,  虽然不影响真机运行, 但是模拟器运行时,  展示缩略图的时候会崩在PhotoView.m的self.addImageButton.py_y = (self.images.count / maxCol) * (self.photoHeight + self.photoMargin);  也就是404行

**Comment by iphone5solo** [comment]
@NateLam 谢谢您的反馈，麻烦把您的测试环境以及报错截图下！

**Comment by NateLam** [comment]
测试环境是xcode8.1,  最低ios 8,  在模拟器才会崩,  把截图里面选中的代码注了就不会崩屏幕快照 2016-12-26 下午10.38.48

**Comment by NateLam** [comment]
我上传了截图, 但是不知道上传成功了没...

**Comment by iphone5solo** [comment]
@NateLam 加我QQ 499491531 备注：GitHub#40

**Comment by iphone5solo** [comment]
@NateLam 加我QQ 499491531 备注：GitHub#40
