### ISSUE TITLE
BUG:未发布状态下，当选择一张图片的size处理

### ISSUE THREAD

**Issue by duwenqi** [iphone5solo/PYPhotoBrowser#44]
@iphone5solo 兄弟，你前几天提交的这个代码，会导致未发布状态下，只选择一张图片的时候 addImageButton显示不出来，所以你应该加个状态条件。

>     // 如果图片为一张，则图片的大小和photosView一致
>     if (count == 1 && !CGSizeEqualToSize(self.bounds.size, CGSizeMake(self.photoMargin, self.photoMargin))) {
>         return self.bounds.size;
>     }

**Comment by iphone5solo** [comment]
@duwenqi  谢谢及时反馈！已处理
