### ISSUE TITLE
滑到最后一张 多滑几次会崩溃

### ISSUE THREAD

**Issue by aptx5788** [iphone5solo/PYPhotoBrowser#50]
滑到最后一张 多滑几次会崩溃

**Comment by iphone5solo** [comment]
@aptx5788 希望能配上gif图 效果更明显 我这边测试不出来！

**Comment by aptx5788** [comment]
数组越界

**Comment by aptx5788** [comment]
iOS 8

**Comment by aptx5788** [comment]
测试不出来？你摁着最后一张使劲往左滑

**Comment by iphone5solo** [comment]
@aptx5788  根据您的描述，现在修复了，欢迎下载最新版测试或者执行pod update!

**Comment by aptx5788** [comment]
👌

**Comment by aptx5788** [comment]
是 page 的问题

**Comment by aptx5788** [comment]
不是 currentPage 的问题

**Comment by iphone5solo** [comment]
你可以尝试自己修复，然后PR给我!

**Comment by aptx5788** [comment]
OK


from Alimail iPhone ------------------Original Mail ------------------From:CoderKo1o <notifications@github.com>Date:2017-01-18 16:47:16Recipient:iphone5solo/PYPhotoBrowser <PYPhotoBrowser@noreply.github.com>CC:Aox.CL <i@aox.design>, Mention <mention@noreply.github.com>Subject:Re: [iphone5solo/PYPhotoBrowser] 滑到最后一张 多滑几次会崩溃 (#50)你可以尝试自己修复，然后PR给我!
