### ISSUE TITLE
在ios8.1出现bug

### ISSUE THREAD

**Issue by lpwcn** [iphone5solo/PYPhotoBrowser#6]
请看gif
http://recordit.co/s9MqUULK7S

**Comment by iphone5solo** [comment]
你好！这个BUG前两天已经有人反馈，已经修复了，你可以下载最新版的再测试一下。

**Comment by lpwcn** [comment]
谢谢，您这个模块做得非常棒，建议加入一个新模式，就是传入图片数组直接打开图片浏览界面，作为一个图片浏览器。

**Comment by iphone5solo** [comment]
其实这个已经有类似的功能，就在那个发布模块。那些图片就是通过传入图片数组的。 你可以去看看
