### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by 77521** [iphone5solo/PYPhotoBrowser#66]
提个不定性bug   有时单击返回时，界面退出不了，怎么解决，这个情况不是每次都出现 ，还有的时候 ，图片有很多时，比如到第四张图片，单击返回，直接返回到第一张，不退出界面，有时候连图都不显示，全黑

**Comment by iphone5solo** [comment]
@77521  加我QQ 备注:#66

**Comment by 77521** [comment]
你QQ多少啊

**Comment by iphone5solo** [comment]
499491531
