### ISSUE TITLE
2个BUG

### ISSUE THREAD

**Issue by Thememont** [iphone5solo/PYPhotoBrowser#7]
1.在最大化的图片右上角继续拉大，放手后会回弹到左上角位置，初步猜测是锚点的问题，正在尝试修改
2.手动拉大图片后无法向右滑动切换图片（即上一张），强行右滑到一定距离后由于死循环闪退

**Comment by iphone5solo** [comment]
第一个BUG，不是因为锚点问题，而是我再设置cell上的contentScrollView的contentSize和contentInset设置时顺序弄反了。导致contentScrollView的contentOffSet变化。现在已经修复，但是第二个BUG我没测出来，能再详细描述一下么？

**Comment by Thememont** [comment]
我直接拍个视频吧
[http://video.weibo.com/show?fid=1034:8c9845721138eb235ee8df0d454496ec](url)

**Comment by Thememont** [comment]
手动放大后的回弹动画，现在有很大概率会位移到右上角

**Comment by iphone5solo** [comment]
嗯嗯,真机和模拟器有差距！我再修复一下。

**Comment by iphone5solo** [comment]
谁修复这两个BUG就pull request 我吧！考虑合并

**Comment by iphone5solo** [comment]
现在这两个BUG已经完全修复了！ 请下载最新版测试。 谢谢您的反馈！ @Thememont
