### ISSUE TITLE
1个bug

### ISSUE THREAD

**Issue by aiOSFuture** [iphone5solo/PYPhotoBrowser#8]
点击发布之后,再次点击示例控制器首页 图片点击无效 

猜测可能是销毁了控制器

**Comment by iphone5solo** [comment]
再详情描述一下， 因为我没测出来！

**Comment by aiOSFuture** [comment]
就是说,在主界面导航栏点击了发布后,然后直接返回主界面,主界面上的逻辑都不能处理了

**Comment by iphone5solo** [comment]
你是在哪个版本的模拟器上测试的？ 你测试的是最新版的代码么？ 我测试都没问题，您可以先下载最新版的代码测试，如果还有问题就说一下测试的模拟器。或者方便的话录个视频啥的。

**Comment by aiOSFuture** [comment]
留个qq什么的,互相学习,这里传东西太慢了

**Comment by iphone5solo** [comment]
499491531
