### ISSUE TITLE
添加在cell上时，图片会占用滑动事件

### ISSUE THREAD

**Issue by ldy694** [iphone5solo/PYPhotoBrowser#83]
具体情况为，在cell上添加了九宫格展示，如果滑动tableview时手指是从图片位置开始的，就没法滑动，事件被占用，但是把图片点开过一次之后，再和刚才同样的方法滑动就可以滑动了

**Comment by ldy694** [comment]
测试手机为6sp  ios10.3.2

**Comment by iphone5solo** [comment]
@ldy694  我按照你说的环境来测试，并没有测试到您所说的问题。请问是使用最新版的么？

**Comment by ldy694** [comment]
@iphone5solo 另一部6sp 9.3.2也会存在这一问题  目前只在测试手机为7  ios10.2 时不存在这个问题 。三部手机匀为真机测试。
以下为集成的相关库
pod 'SDWebImage', '~> 4.0.0'
pod 'DACircularProgress', '~> 2.3.1'
pod 'FLAnimatedImage', '~> 1.0.12'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'PYPhotoBrowser', '~> 1.5.0'

**Comment by ldy694** [comment]
@iphone5solo 
![wx20170608-125101](https://user-images.githubusercontent.com/10148802/26912810-799ac7d2-4c49-11e7-9782-574dbd3a1d32.png)
![wx20170608-125135](https://user-images.githubusercontent.com/10148802/26912811-799c859a-4c49-11e7-8211-2dba4773c2e7.png)
![wx20170608-125146](https://user-images.githubusercontent.com/10148802/26912812-799f2af2-4c49-11e7-84d4-01c69c3a8be3.png)
![wx20170608-125217](https://user-images.githubusercontent.com/10148802/26912813-799f8024-4c49-11e7-8c57-49baef80327a.png)
还有，5s在10.3.2系统下也有问题

**Comment by ldy694** [comment]
我给你发两个视频到你QQ邮箱上你可以看一下

**Comment by iphone5solo** [comment]
@ldy694 我看了你的视频，应该是你在某个地方修改了默认的`photosView`的`contentSize`，给你提供一个解决方案。直接在合适的地方设置`photosView.scrollEnable = NO`即可

**Comment by ldy694** [comment]
@iphone5solo 谢谢，问题已解决。
添加完数据后更新一下约束是因为如果我不更新，photosView会不显示，今天刚集成你的插件，具体原因我没细查，现在一切都是正常的了，谢谢。
