### ISSUE TITLE
首次点击打开长图的bug

### ISSUE THREAD

**Issue by chengxianghe** [iphone5solo/PYPhotoBrowser#9]
上下不能滑动了
可以用此图片测试:
http://ww4.sinaimg.cn/bmiddle/406ef017jw1ec40av2nscj20ip4p0b29.jpg

**Comment by iphone5solo** [comment]
谢谢您的反馈。 最近快要回家过所谓的“暑假”了，所以可能来不及更新。 可以先自己尝试修复。 等我开学来。 尽快修复 实在有些抱歉了。

**Comment by iphone5solo** [comment]
你好，这个长度不能滑动已经修复，欢迎下载最新版测试。 谢谢您的反馈！祝您生活愉快！ @chengxianghe

**Comment by chengxianghe** [comment]
不客气的, 感谢及时处理
