### ISSUE TITLE
同时点击两个图片，会导致程序一直处于图片浏览状态

### ISSUE THREAD

**Issue by zhaoyunyi** [iphone5solo/PYPhotoBrowser#90]
同时点击两个小图片，进入大图浏览状态。会有两个大图浏览状态，点击一下，会消失掉一个，叠在下面的一个点击就无效了

**Comment by iphone5solo** [comment]
@zhaoyunyi 谢谢您的反馈，现在已经修复！欢迎下载最新版测试！
